name: Auto Adsense Script Addition

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Check if adsense.go exists
        run: |
          if [ -f "adsense.go" ]; then
            echo "adsense.go exists"
          else
            echo "adsense.go does not exist, exiting workflow."
            exit 1
          fi

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17'

      - name: Run Go Script
        run: go run adsense.go

      - name: Get Date
        run: echo "DATE=$(date +'%Y-%m-%d')" >> $GITHUB_STATE

      - name: Check for Changes
        run: |
          if git diff --exit-code; then
            echo "CHANGES=false" >> $GITHUB_STATE
          else
            echo "CHANGES=true" >> $GITHUB_STATE
          fi

      - name: Check if GITHUB_STATE file exists
        run: |
          ls -l $GITHUB_STATE || echo "$GITHUB_STATE does not exist"

      - name: Read Changes from State
        id: read_state
        run: echo "CHANGES=$(cat $GITHUB_STATE | grep CHANGES)" >> $GITHUB_STATE

      - name: Commit and Push Changes
        if: steps.read_state.outputs.CHANGES == 'CHANGES=true'
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          git add .
          git commit -m "Add Google Adsense script on $DATE"
          git push

      - name: Display Message if Nothing Changed
        if: steps.read_state.outputs.CHANGES == 'CHANGES=false'
        run: echo "Nothing changed, nothing to commit"
